// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBwUuJ8-W57ZHtPK0dFXp0KhiHAR9N3rs',
    appId: '1:210887198461:web:e4f11913a415dbe57ee094',
    messagingSenderId: '210887198461',
    projectId: 'fixme-2025',
    authDomain: 'fixme-2025.firebaseapp.com',
    databaseURL: 'https://fixme-2025-default-rtdb.firebaseio.com',
    storageBucket: 'fixme-2025.firebasestorage.app',
    measurementId: 'G-4CXW2VTCZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiYO9T-etXTR8Qb-PB6HELuhO1aAwm0pk',
    appId: '1:210887198461:android:b31913d63492cad57ee094',
    messagingSenderId: '210887198461',
    projectId: 'fixme-2025',
    databaseURL: 'https://fixme-2025-default-rtdb.firebaseio.com',
    storageBucket: 'fixme-2025.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBwUuJ8-W57ZHtPK0dFXp0KhiHAR9N3rs',
    appId: '1:210887198461:web:35d78ab2420d48ea7ee094',
    messagingSenderId: '210887198461',
    projectId: 'fixme-2025',
    authDomain: 'fixme-2025.firebaseapp.com',
    databaseURL: 'https://fixme-2025-default-rtdb.firebaseio.com',
    storageBucket: 'fixme-2025.firebasestorage.app',
    measurementId: 'G-GXB5CTKWDK',
  );

}